### PR TITLE
Merge with POSIX Threads for Windows 2.10.0

### PR DESCRIPTION
**Pull request by nicolaichuk**
Merge with POSIX Threads for Windows 2.10.0 http://sourceforge.net/p/pthreads4w/code/ci/master/tree/

Conflicts:
    ChangeLog
    dll.c
    pthread_win32_attach_detach_np.c
    sem_init.c
    tests/common.mk

### CODE REVIEW

**Comment by nicolaichuk** [comment]
ping?

**Comment by GerHobbelt** [comment]
Hi, thanks for the pullreq; I see you pulled in a whole streak of new work from the original repo at sourceforge. 

It merged without conflicts, however diff inspection shows me a few changes in the original package which I need to pour over myself (as at first glance it looks like a few bits are dialed down to WinCE expectations for everyone).

Also the MSVC20xx projects need to be updated as they expect the old fileset and those projects working is of prime importance to me.

Right now as I've little time available for this project so I merged it into a branch and will have a look at the diffs that bother me a bit later on (expect a few weeks delay there; other tasks have priority, alas).

Until this is merged into my `master` I keep the issue open as a reminder for myself at least.

**Comment by nicolaichuk** [comment]
Thanks for the answer.

**Comment by nicolaichuk** [comment]
ping...

Do you plan to follow the changes in the original repository and apply changes to your version? )

https://sourceforge.net/p/pthreads4w/code/commit_browser

**Comment by GerHobbelt** [comment]
🤯 That took ages... Thanks for the work you put in!

**Pull request merged**
